name: ci

on: [push]

jobs:
  tests:
    name: Tests with Foundry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff Neo Compiler
        uses: cakevm/huff-neo-toolchain@v1
        with:
          version: latest

      - name: Run Tests
        run: forge test -vvv

  scripts:
    strategy:
      fail-fast: true
    name: Run Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Huff Neo Compiler
        uses: cakevm/huff-neo-toolchain@v1
        with:
          version: latest

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
        continue-on-error: true

      - name: Run scripts
        run: |
          ls -lsa
          ls script/
          for file in script/*; do
            forge script $file -vvvv
          done